# The minimal kafka service
# github.com/yeasy/docker-compose-files

# * zk: zk node for kafka
# * kafka: kafka service, will default to connect to zookeeper
# * cli: client to test kafka service

version: '2'

services:
  zookeeper:
    image: yeasy/kafka:latest
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"  # zk connection port
    command: bash -c 'bash /tmp/start_zk.sh'

  kafka0: # kafka service
    image: yeasy/kafka:latest
    container_name: kafka0
    hostname: kafka0
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=0 # when bootup, will read this and update the server.properties
    depends_on:
      - zookeeper
    command: bash -c 'bash /tmp/start_kafka.sh'

  kafka1: # kafka service
    image: yeasy/kafka:latest
    container_name: kafka1
    hostname: kafka1
    ports:
      - "9093:9092"
    environment:
      - KAFKA_BROKER_ID=1 # when bootup, will read this and update the server.properties
    depends_on:
      - zookeeper
    command: bash -c 'bash /tmp/start_kafka.sh'

  kafka2: # kafka service
    image: yeasy/kafka:latest
    container_name: kafka2
    hostname: kafka2
    ports:
      - "9094:9092"
    environment:
      - KAFKA_BROKER_ID=2 # when bootup, will read this and update the server.properties
    depends_on:
      - zookeeper
    command: bash -c 'bash /tmp/start_kafka.sh'

  cli:  # used for testing kafka cmds, see /tmp/*.sh
    image: yeasy/kafka:latest
    container_name: cli
    hostname: cli
    environment:
      - ZK_HOST=zookeeper # zk host to connect to
      - KAFKA_HOST=kafka1 # customized the kafka broker to send
    command: bash -c 'while true; do sleep 20200116; done'
